package gate

import (
	"regexp"
)

// RulePattern pairs a pre-compiled regex with its diagnostic label and fix suggestion.

type RulePattern struct {
	Pattern        *regexp.Regexp
	Label          string
	Recommendation string
}

var Claudisms = []RulePattern{
	{
		Pattern:        regexp.MustCompile("(?i)\\bsit with (?:this|that|these|the realization|the fact|the idea)\\b"),
		Label:          "Reflective Posing ('sit with this')",
		Recommendation: "Cut phrase; state the technical conclusion directly.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bthe physics of (?:the problem|software|code|systems?|engineering|the cluster)\\b"),
		Label:          "Metaphorical Physics ('the physics of...')",
		Recommendation: "Replace with concrete constraints: 'hardware limits', 'network boundaries', 'kernel invariants'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\b(?:does|doing)\\s+(?:the|real)\\s+work\\b"),
		Label:          "Epistemic Fluff ('doing real work')",
		Recommendation: "Specify the exact mechanism: 'enforces state replication', 'indexes foreign keys'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\b(?:an?|the)\\s+honest\\s+(?:take|assessment|look|conversation)\\b|\\bhonestly\\s+speaking\\b"),
		Label:          "Performative Candor ('honest take')",
		Recommendation: "Cut entirely; state the finding directly.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bexact grain\\b"),
		Label:          "Claudish Dialect ('exact grain')",
		Recommendation: "Use 'granularity', 'byte offset', or 'resolution'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bcompounds? over time\\b"),
		Label:          "Metaphorical Compounding ('compounds over time')",
		Recommendation: "Specify the exact mechanical accumulation, such as lock contention or unmaintained code paths.",
	},
}

var LoadBearingPattern = regexp.MustCompile("(?i)\\bload[- ]bearing\\b")

var AllowedLoadBearingNouns = map[string]bool{
	"beam":           true,
	"beams":          true,
	"cable":          true,
	"cables":         true,
	"column":         true,
	"columns":        true,
	"database":       true,
	"databases":      true,
	"endpoint":       true,
	"endpoints":      true,
	"girder":         true,
	"girders":        true,
	"index":          true,
	"indices":        true,
	"infrastructure": true,
	"member":         true,
	"members":        true,
	"node":           true,
	"nodes":          true,
	"partition":      true,
	"partitions":     true,
	"pillar":         true,
	"pillars":        true,
	"pipe":           true,
	"pipes":          true,
	"schema":         true,
	"schemas":        true,
	"service":        true,
	"services":       true,
	"shard":          true,
	"shards":         true,
	"structure":      true,
	"structures":     true,
	"substrate":      true,
	"substrates":     true,
	"table":          true,
	"tables":         true,
	"truss":          true,
	"trusses":        true,
	"wall":           true,
	"walls":          true,
	"wire":           true,
	"wires":          true,
}

var AITells = []RulePattern{
	{
		Pattern:        regexp.MustCompile("(?i)\\bdelv(?:e|es|ed|ing)\\b"),
		Label:          "Generic AI Tell ('delve')",
		Recommendation: "Replace with 'inspect', 'analyze', 'examine', or 'profile'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\btapestry\\b"),
		Label:          "Generic AI Tell ('tapestry')",
		Recommendation: "Cut or replace with concrete architecture description.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bbeacon\\b"),
		Label:          "Generic AI Tell ('beacon')",
		Recommendation: "Cut theatrical metaphor; state system purpose.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\b(?:serves?|stands?|is|are)\\s+as\\s+a\\s+testament\\s+to\\b|\\btestament\\s+to\\b"),
		Label:          "Copular Inflation ('testament to')",
		Recommendation: "Replace with 'proves', 'shows', or 'demonstrates'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bparamount\\b"),
		Label:          "Generic AI Tell ('paramount')",
		Recommendation: "Use 'critical', 'mandatory', or explain consequence of omission.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bmultifaceted\\b"),
		Label:          "Generic AI Tell ('multifaceted')",
		Recommendation: "Detail the specific components or dimensions.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bintertwined\\b"),
		Label:          "Generic AI Tell ('intertwined')",
		Recommendation: "Specify the coupling or dependency relationship.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bparsimoniously\\b"),
		Label:          "Lexical Register Intrusion ('parsimoniously')",
		Recommendation: "Use 'sparingly', 'minimally', or state the exact limit.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bnuanced\\s+(?:landscape|realm|interplay|tapestry)\\b"),
		Label:          "Generic AI Tell ('nuanced landscape')",
		Recommendation: "Describe the specific architectural trade-offs.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bseamless(?:ly)?\\b"),
		Label:          "Generic AI Tell ('seamless')",
		Recommendation: "Specify latency, integration protocol, or error boundaries.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bcrucial foundation\\b"),
		Label:          "Generic AI Tell ('crucial foundation')",
		Recommendation: "State the exact prerequisite dependency.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\b(?:formal\\s+)?axiomatic\\s+compression\\s+operators?\\b"),
		Label:          "Pseudo-Intellectual AI Tell ('axiomatic compression operator')",
		Recommendation: "Use 'precise technical terms' or 'exact behavioral guarantees'.",
	},
}

var PerformativeWinks = []RulePattern{
	{
		Pattern:        regexp.MustCompile("(?i)\\bsee what i did (?:there|here)\\b"),
		Label:          "Conversational Wink",
		Recommendation: "Cut performative humor.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bhere'?s the kicker\\b"),
		Label:          "Conversational Wink ('Here's the kicker')",
		Recommendation: "State the finding directly.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\blet(?:'s|\\s+us)\\s+dive\\s+in\\b"),
		Label:          "Performative Banter ('Let's dive in')",
		Recommendation: "Begin immediately with technical substance.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bbuckle up\\b"),
		Label:          "Performative Banter ('Buckle up')",
		Recommendation: "Cut theatrical banter.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bat the end of the day\\b"),
		Label:          "Performative Clich\u00e9 ('At the end of the day')",
		Recommendation: "State conclusion directly.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bjourney worth taking\\b"),
		Label:          "Performative Banter ('journey worth taking')",
		Recommendation: "Cut literary melodrama.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\blet(?:'s|\\s+us)\\s+unpack\\b"),
		Label:          "Meta-Padding ('Let's unpack')",
		Recommendation: "Explain the mechanism directly without announcing it.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\blet(?:'s|\\s+us)\\s+take\\s+a\\s+step\\s+back\\b"),
		Label:          "Meta-Padding ('Let's take a step back')",
		Recommendation: "Address the topic directly.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bok,?\\s*i'?m becoming almost meta\\b"),
		Label:          "Performative Meta-Commentary",
		Recommendation: "Cut self-referential commentary.",
	},
}

var SycophancyPatterns = []RulePattern{
	{
		Pattern:        regexp.MustCompile("(?i)\\byou(?:'re| are) (?:completely|absolutely|totally) right\\b"),
		Label:          "Sycophantic Validation",
		Recommendation: "Cut agreement; deliver analysis directly.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)(?:\\bthat(?:'s|\\s+is)\\s+a\\s+|\\b)(?:great|profound|fantastic|wonderful|excellent|good)\\s+(?:point|question|catch|observation)\\b"),
		Label:          "Sycophantic Flattery",
		Recommendation: "Answer the prompt directly without evaluating the user's intelligence.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bi(?:'d| would) (?:be delighted|be happy|love) to (?:help|assist)\\b"),
		Label:          "Sycophantic Preambles",
		Recommendation: "Start directly with code, diff, or diagnostics.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)^\\s*(?:certainly|sure thing|of course|gladly)[!,.]?\\s*"),
		Label:          "Sycophantic Opening ('Certainly!')",
		Recommendation: "Start directly with the answer.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bi hope this helps\\b"),
		Label:          "Customer-Support Sign-Off",
		Recommendation: "End at the technical verification step.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bhappy coding!?\\b"),
		Label:          "Customer-Support Sign-Off",
		Recommendation: "End cleanly at the technical step.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\b(?:let me know if|feel free to|don'?t hesitate to)\\s+(?:you\\s+have\\s+any\\s+questions|reach\\s+out|ask|there'?s\\s+anything\\s+else)\\b"),
		Label:          "Customer-Support Sign-Off",
		Recommendation: "End cleanly at the technical verification step.",
	},
}

var TailingClauses = []RulePattern{
	{
		Pattern:        regexp.MustCompile("(?i),\\s*(?:highlighting|underscoring|fostering|ensuring|paving the way|showcasing|embodying|exemplifying|bolstering|underpinning)\\b"),
		Label:          "Tailing Participial Clause (-ing appendage)",
		Recommendation: "End sentence at the period. Avoid moralizing or teleological appendages.",
	},
}

var LightVerbNominals = []RulePattern{
	{
		Pattern:        regexp.MustCompile("(?i)\\bperform an? allocation\\b"),
		Label:          "Light Verb Nominal ('perform an allocation')",
		Recommendation: "Use 'allocate'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bfacilitate the optimization of\\b"),
		Label:          "Light Verb Nominal ('facilitate optimization')",
		Recommendation: "Use 'optimize'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bmake an? adjustment to\\b"),
		Label:          "Light Verb Nominal ('make an adjustment')",
		Recommendation: "Use 'adjust'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bconduct an evaluation of\\b"),
		Label:          "Light Verb Nominal ('conduct evaluation')",
		Recommendation: "Use 'evaluate'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bachieve the mitigation of\\b"),
		Label:          "Light Verb Nominal ('achieve mitigation')",
		Recommendation: "Use 'mitigate'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bprovide an explanation of\\b"),
		Label:          "Light Verb Nominal ('provide an explanation')",
		Recommendation: "Use 'explain'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bexecute a termination of\\b"),
		Label:          "Light Verb Nominal ('execute a termination of')",
		Recommendation: "Use 'terminate'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\breach a determination regarding\\b"),
		Label:          "Light Verb Nominal ('reach a determination regarding')",
		Recommendation: "Use 'determine'.",
	},
	{
		Pattern:        regexp.MustCompile("(?i)\\bperform an execution of\\b"),
		Label:          "Light Verb Nominal ('perform an execution of')",
		Recommendation: "Use 'execute'.",
	},
}

var ValidDomainTechnicalNouns = map[string]bool{
	"abstraction":       true,
	"abstractions":      true,
	"absurdities":       true,
	"absurdity":         true,
	"achievement":       true,
	"achievements":      true,
	"acknowledgement":   true,
	"acknowledgment":    true,
	"acquisition":       true,
	"action":            true,
	"adherence":         true,
	"affinity":          true,
	"aggregation":       true,
	"algorithm":         true,
	"alignment":         true,
	"allocation":        true,
	"ambiguity":         true,
	"animation":         true,
	"antigravity":       true,
	"appearance":        true,
	"application":       true,
	"argument":          true,
	"assertion":         true,
	"assignment":        true,
	"assistance":        true,
	"associativity":     true,
	"atomicity":         true,
	"attachment":        true,
	"authentication":    true,
	"authorities":       true,
	"authority":         true,
	"authorization":     true,
	"availability":      true,
	"balance":           true,
	"cadence":           true,
	"cadences":          true,
	"calculation":       true,
	"calibration":       true,
	"cancellation":      true,
	"capacitance":       true,
	"capacity":          true,
	"cardinality":       true,
	"chance":            true,
	"circumlocution":    true,
	"circumlocutions":   true,
	"circumstance":      true,
	"clarification":     true,
	"clarifications":    true,
	"classification":    true,
	"clearance":         true,
	"coherence":         true,
	"comment":           true,
	"comments":          true,
	"commitment":        true,
	"communication":     true,
	"communities":       true,
	"community":         true,
	"commutativity":     true,
	"compartment":       true,
	"compatibility":     true,
	"compensation":      true,
	"competence":        true,
	"competition":       true,
	"competitions":      true,
	"complexity":        true,
	"compliance":        true,
	"computability":     true,
	"computation":       true,
	"concavity":         true,
	"concurrence":       true,
	"concurrency":       true,
	"condition":         true,
	"conference":        true,
	"confidence":        true,
	"configuration":     true,
	"confirmation":      true,
	"confirmations":     true,
	"conformance":       true,
	"conjunction":       true,
	"conjunctions":      true,
	"connection":        true,
	"connectivity":      true,
	"consequence":       true,
	"consistency":       true,
	"construction":      true,
	"consumption":       true,
	"containment":       true,
	"contention":        true,
	"continuation":      true,
	"continuity":        true,
	"convention":        true,
	"conventions":       true,
	"convergence":       true,
	"convexity":         true,
	"convolution":       true,
	"correction":        true,
	"criticalities":     true,
	"criticality":       true,
	"deallocation":      true,
	"decidability":      true,
	"decomposition":     true,
	"decompositions":    true,
	"decompression":     true,
	"decoupling":        true,
	"decouplings":       true,
	"decrement":         true,
	"decryption":        true,
	"deduplication":     true,
	"definition":        true,
	"demonstration":     true,
	"density":           true,
	"deployment":        true,
	"derivation":        true,
	"description":       true,
	"deserialization":   true,
	"destination":       true,
	"development":       true,
	"developments":      true,
	"difference":        true,
	"differentiability": true,
	"dimension":         true,
	"disambiguation":    true,
	"disambiguations":   true,
	"distance":          true,
	"distribution":      true,
	"distributivity":    true,
	"divergence":        true,
	"document":          true,
	"documentation":     true,
	"dominance":         true,
	"dominances":        true,
	"durability":        true,
	"duration":          true,
	"elasticity":        true,
	"element":           true,
	"emission":          true,
	"encryption":        true,
	"entanglement":      true,
	"entanglements":     true,
	"entities":          true,
	"entitlement":       true,
	"entity":            true,
	"environment":       true,
	"equality":          true,
	"equation":          true,
	"equipment":         true,
	"eradication":       true,
	"eviction":          true,
	"evidence":          true,
	"evolution":         true,
	"exception":         true,
	"execution":         true,
	"existence":         true,
	"expectation":       true,
	"experiment":        true,
	"explanation":       true,
	"expressivity":      true,
	"extensibility":     true,
	"fence":             true,
	"formation":         true,
	"formations":        true,
	"foundation":        true,
	"foundations":       true,
	"fraction":          true,
	"fragment":          true,
	"fragmentation":     true,
	"frequency":         true,
	"friction":          true,
	"frictions":         true,
	"frustration":       true,
	"frustrations":      true,
	"function":          true,
	"functionalities":   true,
	"functionality":     true,
	"generalization":    true,
	"generation":        true,
	"glance":            true,
	"granularity":       true,
	"guidance":          true,
	"heterogeneity":     true,
	"hierarchy":         true,
	"homogeneity":       true,
	"idempotence":       true,
	"idempotency":       true,
	"identity":          true,
	"immutability":      true,
	"impedance":         true,
	"implementation":    true,
	"impossibility":     true,
	"increment":         true,
	"inequality":        true,
	"inference":         true,
	"inflation":         true,
	"inflations":        true,
	"information":       true,
	"ingestion":         true,
	"inheritance":       true,
	"initialization":    true,
	"instance":          true,
	"instantiation":     true,
	"instruction":       true,
	"instrument":        true,
	"integrability":     true,
	"integrity":         true,
	"interaction":       true,
	"interference":      true,
	"interoperability":  true,
	"interpretation":    true,
	"interrogation":     true,
	"interrogations":    true,
	"interruption":      true,
	"intersection":      true,
	"intuition":         true,
	"intuitions":        true,
	"invalidation":      true,
	"invariance":        true,
	"iteration":         true,
	"latency":           true,
	"linearity":         true,
	"linearizability":   true,
	"linearization":     true,
	"locality":          true,
	"location":          true,
	"lucidity":          true,
	"maintainability":   true,
	"maintenance":       true,
	"majority":          true,
	"management":        true,
	"manipulation":      true,
	"measurement":       true,
	"mention":           true,
	"mentions":          true,
	"migration":         true,
	"minority":          true,
	"misconception":     true,
	"misconceptions":    true,
	"misprediction":     true,
	"mispredictions":    true,
	"modification":      true,
	"modularity":        true,
	"monotonicity":      true,
	"motion":            true,
	"motions":           true,
	"multiplicity":      true,
	"mutability":        true,
	"mutation":          true,
	"nominalization":    true,
	"nominalizations":   true,
	"nonlinearity":      true,
	"normalization":     true,
	"observability":     true,
	"occurrence":        true,
	"operation":         true,
	"optimization":      true,
	"orientation":       true,
	"ornamentation":     true,
	"ornamentations":    true,
	"pagination":        true,
	"paradigm":          true,
	"paradigms":         true,
	"parameterization":  true,
	"parity":            true,
	"partition":         true,
	"performance":       true,
	"permission":        true,
	"permutation":       true,
	"persistence":       true,
	"placement":         true,
	"population":        true,
	"position":          true,
	"possibilities":     true,
	"possibility":       true,
	"precision":         true,
	"presence":          true,
	"presences":         true,
	"priority":          true,
	"probability":       true,
	"production":        true,
	"profundities":      true,
	"profundity":        true,
	"programmability":   true,
	"prohibition":       true,
	"prohibitions":      true,
	"projection":        true,
	"propagation":       true,
	"proportion":        true,
	"proposition":       true,
	"propositions":      true,
	"provenance":        true,
	"punctuation":       true,
	"punctuations":      true,
	"quality":           true,
	"quantities":        true,
	"quantity":          true,
	"quantization":      true,
	"reachability":      true,
	"reaction":          true,
	"readability":       true,
	"realities":         true,
	"reality":           true,
	"reallocation":      true,
	"reception":         true,
	"receptions":        true,
	"reconciliation":    true,
	"recoverability":    true,
	"recurrence":        true,
	"redirection":       true,
	"reducibility":      true,
	"reduction":         true,
	"reference":         true,
	"refinement":        true,
	"reflection":        true,
	"reflexivity":       true,
	"registration":      true,
	"regression":        true,
	"regularity":        true,
	"rejection":         true,
	"rejections":        true,
	"relation":          true,
	"reliability":       true,
	"reluctance":        true,
	"remediation":       true,
	"remediations":      true,
	"replacement":       true,
	"replication":       true,
	"representation":    true,
	"reproducibility":   true,
	"requirement":       true,
	"residence":         true,
	"resistance":        true,
	"resolution":        true,
	"resonance":         true,
	"rotation":          true,
	"saturation":        true,
	"scalability":       true,
	"science":           true,
	"section":           true,
	"segment":           true,
	"segmentation":      true,
	"sensitivity":       true,
	"sentence":          true,
	"sentences":         true,
	"sentience":         true,
	"separation":        true,
	"sequence":          true,
	"serializability":   true,
	"serialization":     true,
	"session":           true,
	"significance":      true,
	"silence":           true,
	"simplification":    true,
	"simplifications":   true,
	"simulation":        true,
	"singularity":       true,
	"solution":          true,
	"specialization":    true,
	"specification":     true,
	"speculation":       true,
	"speculations":      true,
	"stability":         true,
	"stance":            true,
	"statement":         true,
	"substance":         true,
	"substitution":      true,
	"synchronicity":     true,
	"synchronization":   true,
	"telemetries":       true,
	"telemetry":         true,
	"termination":       true,
	"terminologies":     true,
	"terminology":       true,
	"tolerance":         true,
	"topology":          true,
	"traceability":      true,
	"tractability":      true,
	"tradition":         true,
	"traditions":        true,
	"transaction":       true,
	"transformation":    true,
	"transition":        true,
	"transitivity":      true,
	"translation":       true,
	"transmission":      true,
	"truncation":        true,
	"uniformities":      true,
	"uniformity":        true,
	"utility":           true,
	"validation":        true,
	"validity":          true,
	"variance":          true,
	"verbosity":         true,
	"verification":      true,
	"version":           true,
	"violation":         true,
	"violations":        true,
	"visibility":        true,
}

var UnanchoredThisFollowers = map[string]bool{
	"actually":     true,
	"again":        true,
	"allow":        true,
	"allowed":      true,
	"allows":       true,
	"already":      true,
	"also":         true,
	"always":       true,
	"appear":       true,
	"appeared":     true,
	"appears":      true,
	"applied":      true,
	"applies":      true,
	"apply":        true,
	"are":          true,
	"at":           true,
	"be":           true,
	"became":       true,
	"become":       true,
	"becomes":      true,
	"been":         true,
	"being":        true,
	"break":        true,
	"breaks":       true,
	"broke":        true,
	"broken":       true,
	"by":           true,
	"can":          true,
	"cause":        true,
	"caused":       true,
	"causes":       true,
	"clearly":      true,
	"consist":      true,
	"consisted":    true,
	"consists":     true,
	"contain":      true,
	"contained":    true,
	"contains":     true,
	"could":        true,
	"create":       true,
	"created":      true,
	"creates":      true,
	"demand":       true,
	"demanded":     true,
	"demands":      true,
	"demonstrate":  true,
	"demonstrated": true,
	"demonstrates": true,
	"depend":       true,
	"depended":     true,
	"depends":      true,
	"did":          true,
	"differ":       true,
	"differed":     true,
	"differs":      true,
	"directly":     true,
	"do":           true,
	"does":         true,
	"doing":        true,
	"done":         true,
	"effectively":  true,
	"eliminate":    true,
	"eliminated":   true,
	"eliminates":   true,
	"ensure":       true,
	"ensured":      true,
	"ensures":      true,
	"essentially":  true,
	"even":         true,
	"expose":       true,
	"exposed":      true,
	"exposes":      true,
	"fail":         true,
	"failed":       true,
	"fails":        true,
	"feel":         true,
	"feels":        true,
	"felt":         true,
	"for":          true,
	"force":        true,
	"forced":       true,
	"forces":       true,
	"from":         true,
	"gave":         true,
	"generate":     true,
	"generated":    true,
	"generates":    true,
	"give":         true,
	"given":        true,
	"gives":        true,
	"guarantee":    true,
	"guaranteed":   true,
	"guarantees":   true,
	"had":          true,
	"handle":       true,
	"handled":      true,
	"handles":      true,
	"happen":       true,
	"happened":     true,
	"happens":      true,
	"has":          true,
	"have":         true,
	"having":       true,
	"held":         true,
	"help":         true,
	"helped":       true,
	"helps":        true,
	"hold":         true,
	"holds":        true,
	"however":      true,
	"implied":      true,
	"implies":      true,
	"imply":        true,
	"in":           true,
	"include":      true,
	"included":     true,
	"includes":     true,
	"increase":     true,
	"increased":    true,
	"increases":    true,
	"indicate":     true,
	"indicated":    true,
	"indicates":    true,
	"induce":       true,
	"induced":      true,
	"induces":      true,
	"initiate":     true,
	"initiated":    true,
	"initiates":    true,
	"instead":      true,
	"introduce":    true,
	"introduced":   true,
	"introduces":   true,
	"is":           true,
	"just":         true,
	"lead":         true,
	"leads":        true,
	"leave":        true,
	"leaves":       true,
	"led":          true,
	"left":         true,
	"look":         true,
	"looked":       true,
	"looks":        true,
	"made":         true,
	"make":         true,
	"makes":        true,
	"manifest":     true,
	"manifested":   true,
	"manifests":    true,
	"may":          true,
	"mean":         true,
	"means":        true,
	"meant":        true,
	"might":        true,
	"mitigate":     true,
	"mitigated":    true,
	"mitigates":    true,
	"must":         true,
	"never":        true,
	"not":          true,
	"occur":        true,
	"occurred":     true,
	"occurs":       true,
	"often":        true,
	"only":         true,
	"prevent":      true,
	"prevented":    true,
	"prevents":     true,
	"protect":      true,
	"protected":    true,
	"protects":     true,
	"prove":        true,
	"proved":       true,
	"proven":       true,
	"proves":       true,
	"provide":      true,
	"provided":     true,
	"provides":     true,
	"rarely":       true,
	"reduce":       true,
	"reduced":      true,
	"reduces":      true,
	"remain":       true,
	"remained":     true,
	"remains":      true,
	"represent":    true,
	"represented":  true,
	"represents":   true,
	"require":      true,
	"required":     true,
	"requires":     true,
	"result":       true,
	"resulted":     true,
	"results":      true,
	"reveal":       true,
	"revealed":     true,
	"reveals":      true,
	"seem":         true,
	"seemed":       true,
	"seems":        true,
	"seldom":       true,
	"serve":        true,
	"served":       true,
	"serves":       true,
	"shall":        true,
	"should":       true,
	"show":         true,
	"showed":       true,
	"shown":        true,
	"shows":        true,
	"simplified":   true,
	"simplifies":   true,
	"simplify":     true,
	"simply":       true,
	"stand":        true,
	"stands":       true,
	"still":        true,
	"stood":        true,
	"suggest":      true,
	"suggested":    true,
	"suggests":     true,
	"therefore":    true,
	"thus":         true,
	"to":           true,
	"trigger":      true,
	"triggered":    true,
	"triggers":     true,
	"violate":      true,
	"violated":     true,
	"violates":     true,
	"was":          true,
	"were":         true,
	"will":         true,
	"with":         true,
	"work":         true,
	"worked":       true,
	"works":        true,
	"would":        true,
	"yield":        true,
	"yielded":      true,
	"yields":       true,
}
